---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-editors"
  version: "0.27.1"
  origin:
    repo: "https://github.com/atomist/rug-editors.git"
    branch: "3de333b4aefd678ae14f196ab155647241de3746"
    sha: "3de333b"

---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"

